apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels: {app: backend}
  template:
    metadata:
      labels: {app: backend}
    spec:
      imagePullSecrets: [{name: harbor-regcred}]
      containers:
      - name: django
        image: 10.0.0.31:80/backend/django-app:latest   # Jenkins 会替换 tag
        ports: [{containerPort: 8000}]
        env:
        - {name: DB_HOST, value: "10.0.0.50"}
        - {name: DB_PORT, value: "3306"}
        - {name: DB_NAME, value: "django_news"}
        - {name: DB_USER, value: "root"}
        - {name: DB_PASSWORD, value: "root"}
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: ClusterIP
  ports: [{port: 8000, targetPort: 8000}]
  selector: {app: backend}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service: {name: backend, port: {number: 8000}}