# Generated by Django 2.0 on 2024-03-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('province', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('county', models.CharField(max_length=20)),
                ('add_detail', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=11)),
                ('user_id', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=130)),
                ('status', models.CharField(max_length=1)),
                ('simple', models.CharField(max_length=300)),
                ('detail', models.CharField(max_length=5000)),
                ('package_detail', models.CharField(max_length=5000)),
                ('package', models.CharField(max_length=5)),
                ('pic', models.CharField(max_length=200)),
                ('market_price', models.CharField(max_length=5)),
                ('sale_price', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=1)),
                ('date', models.DateTimeField()),
                ('price', models.CharField(max_length=10)),
                ('user_id', models.CharField(max_length=30)),
                ('addr_id', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='order_goods',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.CharField(max_length=30)),
                ('goods_id', models.CharField(max_length=30)),
                ('num', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
                ('sex', models.CharField(max_length=1)),
                ('email', models.CharField(max_length=20)),
                ('qq', models.CharField(max_length=15)),
                ('phone', models.CharField(max_length=11)),
            ],
        ),
    ]
