# Generated by Django 3.2.25 on 2025-04-21 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0002_auto_20250421_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='pic',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
