# Generated by Django 3.2.25 on 2025-04-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0003_staff_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tablex',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, null=True)),
                ('num', models.CharField(max_length=20, null=True)),
                ('status', models.CharField(max_length=20, null=True)),
                ('cate', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='staff',
            name='pic',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
