# Generated by Django 3.2.25 on 2025-04-21 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0004_auto_20250421_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablex',
            name='de',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
